In [1]:
import geopandas as gpd
import pandas as pd
from tqdm import tqdm
import requests
import numpy as np

In [2]:
url = 'https://www.nadlan.gov.il/Nadlan.REST/Main/GetAssestAndDeals'

list_res=[]

In [3]:
city_name = "בת ים"
objid = "6200"
X =176423.26082654
Y=657969.2728939

In [4]:
df_full=pd.DataFrame()

In [6]:
for pagenum in tqdm(range(1,2)):
    data = {"MoreAssestsType":0,"FillterRoomNum":0,"GridDisplayType":0,
            "ResultLable":city_name,
            "ResultType":1,
            "ObjectID":objid,"ObjectIDType":"text","ObjectKey":"UNIQ_ID",
            "DescLayerID":"SETL_MID_POINT","Alert":None,
            "X":X,
            "Y":Y,
            "Gush":"","Parcel":"","showLotParcel":True,
            "showLotAddress":True,"OriginalSearchString":city_name,"MutipuleResults":False,
            "ResultsOptions":None,
            "CurrentLavel":2,
            "Navs":[{"text":"מחוז תל אביב - יפו","url":None,"order":1}],
            "QueryMapParams":{"QueryToRun":None,"QueryObjectID":objid,"QueryObjectType":"number",
                              "QueryObjectKey":"SETL_CODE","QueryDescLayerID":"KSHTANN_SETL_AREA","SpacialWhereClause":None},
            "isHistorical":True,
            "PageNo":pagenum,
            "OrderByFilled":"DEALDATETIME","OrderByDescending":True,"Distance":0}
    result = requests.post(url, json=data).json()
    list_res.append(result)

for r in list_res:
    df= pd.DataFrame(r["AllResults"])
    df_full = pd.concat([df,df_full])

100%|█████████████████████████████████████████████| 1/1 [00:06<00:00,  6.35s/it]

In [7]:
df_full

,DEALDATE,DEALDATETIME,FULLADRESS,DISPLAYADRESS,GUSH,DEALNATUREDESCRIPTION,ASSETROOMNUM,FLOORNO,DEALNATURE,DEALAMOUNT,NEWPROJECTTEXT,PROJECTNAME,BUILDINGYEAR,YEARBUILT,BUILDINGFLOORS,KEYVALUE,TYPE,POLYGON_ID,TREND_IS_NEGATIVE,TREND_FORMAT
0,29.05.2024,2024-05-29T00:00:00,"סוקולוב 1, בת ים",סוקולוב 1,7145-101-30,דירה בבית קומות,4,חמישית,92,"2,700,000",1,רוטשילד,1960,,3,6206113400,1,7145-101,False,
1,27.05.2024,2024-05-27T00:00:00,"הפטמן 2, בת ים",הפטמן 2,7130-255-14,דירה בבית קומות,4,שלישית,71.45,"1,820,000",,None,1970,,7,6206063000,1,7130-255,False,
2,27.05.2024,2024-05-27T00:00:00,"סוקולוב 10, בת ים",סוקולוב 10,7145-12-13,דירה בבית קומות,3,שניה,48.29,"1,930,000",,None,1970,,3,6206055600,1,7145-12,False,10% ב 2.7 שנים
3,27.05.2024,2024-05-27T00:00:00,"הרצל 62, בת ים",הרצל 62,7141-4-62,דירה בבית קומות,4,שישית,100,"2,840,000",1,פנינת הרצל,2020,,10,6206033400,1,7141-4,False,
4,27.05.2024,2024-05-27T00:00:00,"העצמאות 67, בת ים",העצמאות 67,7147-115-153,דירה בבית קומות,5,שביעית,107.69,"2,120,000",,None,1970,,21,6206063900,1,7147-115,False,
5,26.05.2024,2024-05-26T00:00:00,"חלמית 15, בת ים",חלמית 15,6997-271-19,דירה בבית קומות,3,ראשונה,63.50,"1,778,000",,None,1970,,4,6206058050,1,6997-271,False,
6,26.05.2024,2024-05-26T00:00:00,"החשמונאים 74, בת ים",החשמונאים 74,7130-198-9,דירה בבית קומות,3,עשירית,76,"2,500,000",,None,1950,2026,2,6206160850,1,7130-198,False,
7,26.05.2024,2024-05-26T00:00:00,"יצחק שדה 33, בת ים",יצחק שדה 33,7154-296-37,דירה בבית קומות,3,חמישית,62,"2,080,000",,None,1970,,8,6206002800,1,7154-296,False,54% ב 5.9 שנים
8,26.05.2024,2024-05-26T00:00:00,"ניצנה 11, בת ים",ניצנה 11,7160-317-6,דירה בבית קומות,2,שניה,48,"1,450,000",,None,1950,,3,6206004900,1,7160-317,False,
9,22.05.2024,2024-05-22T00:00:00,"כהן אלי 26, בת ים",כהן אלי 26,7128-64-5,דירה בבית קומות,3,ראשונה,48,"1,720,000",,None,1970,,4,6205957000,1,7128-64,False,
10,22.05.2024,2024-05-22T00:00:00,"עגנון 5, בת ים",עגנון 5,7139-148-6,דירה בבית קומות,6,שלישית ורביעית,104.29,"2,650,000",,None,1970,2008,7,6205857200,1,7139-148,False,192% ב 23.3 שנים
11,21.05.2024,2024-05-21T00:00:00,"הרב לוי 17, בת ים",הרב לוי 17,7128-164-1,דירה בבית קומות,3,ראשונה,57.45,"2,150,000",,None,1970,,4,6205849850,1,7128-164,False,83% ב 8.5 שנים
12,21.05.2024,2024-05-21T00:00:00,"הזית 3, בת ים",הזית 3,7151-303-30,דירה בבית קומות,3,שניה,54.10,"1,580,000",,None,1970,,3,6205839050,1,7151-303,False,
13,21.05.2024,2024-05-21T00:00:00,"הרב מימון 36, בת ים",הרב מימון 36,7178-9-46,דירה בבית קומות,4,שלישית,85.20,"2,090,000",,None,1970,,4,6205888150,1,7178-9,False,
14,20.05.2024,2024-05-20T00:00:00,"השרון 2, בת ים",השרון 2,7128-94-13,דירה בבית קומות,3,שניה,46.58,"1,750,000",,None,1970,,4,6205799950,1,7128-94,False,
15,20.05.2024,2024-05-20T00:00:00,"ארלוזורוב 5, בת ים",ארלוזורוב 5,7146-241-25,דירה בבית קומות,5,חמישית,127,"3,435,000",,None,1950,2024,2,6205895600,1,7146-241,False,
16,20.05.2024,2024-05-20T00:00:00,"יחזקאל דנין 31, בת ים",יחזקאל דנין 31,7136-408-4,דירה בבית קומות,2,ראשונה,40,"1,480,000",,None,1970,,4,6206115000,1,7136-408,False,236% ב 16.1 שנים
17,19.05.2024,2024-05-19T00:00:00,"הצפירה 5, בת ים",הצפירה 5,7142-106-9,דירה בבית קומות,3,שישית,63,"2,256,000",,None,1970,2022,4,6205792900,1,7142-106,False,
18,19.05.2024,2024-05-19T00:00:00,"קדושי קהיר 7, בת ים",קדושי קהיר 7,7148-138-1,דירה בבית קומות,4,חמישית,97,"2,880,000",,None,2024,,None,6205826300,1,7148-138,False,
19,16.05.2024,2024-05-16T00:00:00,"החשמונאים 74, בת ים",החשמונאים 74,7130-198-6,דירה בבית קומות,3,שניה,42.47,"2,531,000",,None,1950,2026,2,6206056900,1,7130-198,False,

In [ ]:
df_full=pd.DataFrame()
for start_n in np.arange(1,2001,200):
    
    for pagenum in tqdm(range(start_n,start_n+200)):
        data = {"MoreAssestsType":0,"FillterRoomNum":0,"GridDisplayType":0,
            "ResultLable":city_name,
            "ResultType":1,
            "ObjectID":objid,"ObjectIDType":"text","ObjectKey":"UNIQ_ID",
            "DescLayerID":"SETL_MID_POINT","Alert":None,
            "X":X,
            "Y":Y,
            "Gush":"","Parcel":"","showLotParcel":True,
            "showLotAddress":True,"OriginalSearchString":city_name,"MutipuleResults":False,
            "ResultsOptions":None,
            "CurrentLavel":2,
            "Navs":[{"text":"מחוז תל אביב - יפו","url":None,"order":1}],
            "QueryMapParams":{"QueryToRun":None,"QueryObjectID":objid,"QueryObjectType":"number",
                              "QueryObjectKey":"SETL_CODE","QueryDescLayerID":"KSHTANN_SETL_AREA","SpacialWhereClause":None},
            "isHistorical":True,
            "PageNo":pagenum,
            "OrderByFilled":"DEALDATETIME","OrderByDescending":True,"Distance":0}
        result = requests.post(url, json=data).json()
        list_res.append(result)
    
    for r in list_res:
        df= pd.DataFrame(r["AllResults"])
        df_full = pd.concat([df,df_full])
    df_full.to_csv(f"batyam_nadlan_pages{start_n}_{start_n+200}.csv")

100%|█████████████████████████████████████████| 200/200 [20:36<00:00,  6.18s/it]
100%|█████████████████████████████████████████| 200/200 [21:04<00:00,  6.32s/it]
100%|█████████████████████████████████████████| 200/200 [21:03<00:00,  6.32s/it]
100%|█████████████████████████████████████████| 200/200 [21:04<00:00,  6.32s/it]
100%|█████████████████████████████████████████| 200/200 [24:39<00:00,  7.40s/it]
100%|█████████████████████████████████████████| 200/200 [20:48<00:00,  6.24s/it]
 35%|██████████████▋                           | 70/200 [07:26<13:42,  6.33s/it]

In [6]:
start_n=801

data = pd.read_csv(f"batyam_nadlan_pages{start_n}_{start_n+200}.csv")

data = data.drop_duplicates()

# df_full=pd.DataFrame()

data

,Unnamed: 0,DEALDATE,DEALDATETIME,FULLADRESS,DISPLAYADRESS,GUSH,DEALNATUREDESCRIPTION,ASSETROOMNUM,FLOORNO,DEALNATURE,...,NEWPROJECTTEXT,PROJECTNAME,BUILDINGYEAR,YEARBUILT,BUILDINGFLOORS,KEYVALUE,TYPE,POLYGON_ID,TREND_IS_NEGATIVE,TREND_FORMAT
0,0,11.05.2010,2010-05-11T00:00:00,"הרב צבי יהודה 5, בת ים",הרב צבי יהודה 5,7124-282-25,דירה בבית קומות,5.0,שביעית,114.88,...,NaN,NaN,2010.0,NaN,8.0,5505313750,1,7124-282,False,NaN
1,1,11.05.2010,2010-05-11T00:00:00,"השר שפירא 3, בת ים",השר שפירא 3,7140-238-20,דירה בבית קומות,2.5,רביעית,52.00,...,NaN,NaN,1970.0,NaN,4.0,5504738900,1,7140-238,False,NaN
2,2,11.05.2010,2010-05-11T00:00:00,"הרב מימון 37, בת ים",הרב מימון 37,7178-8-40,דירה בבית קומות,4.0,רביעית,85.20,...,NaN,NaN,1970.0,NaN,4.0,5506780650,1,7178-8,False,NaN
3,3,10.05.2010,2010-05-10T00:00:00,"הנביאים 54, בת ים",הנביאים 54,7120-154-63,דירה בבית קומות,4.0,קומה ‎16‏,107.50,...,NaN,NaN,2007.0,NaN,35.0,5505019650,1,7120-154,False,29% ב 2.5 שנים
4,4,10.05.2010,2010-05-10T00:00:00,"הרב צבי יהודה 5, בת ים",הרב צבי יהודה 5,7124-282-38,דירה,5.0,שניה,123.65,...,1.0,בית ישראל,2010.0,NaN,8.0,11171538402,1,7124-282,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,15,20.05.2024,2024-05-20T00:00:00,"ארלוזורוב 5, בת ים",ארלוזורוב 5,7146-241-25,דירה בבית קומות,5.0,חמישית,127.00,...,NaN,NaN,1950.0,2024.0,2.0,6205895600,1,7146-241,False,NaN
19996,16,20.05.2024,2024-05-20T00:00:00,"יחזקאל דנין 31, בת ים",יחזקאל דנין 31,7136-408-4,דירה בבית קומות,2.0,ראשונה,40.00,...,NaN,NaN,1970.0,NaN,4.0,6206115000,1,7136-408,False,236% ב 16.1 שנים
19997,17,19.05.2024,2024-05-19T00:00:00,"הצפירה 5, בת ים",הצפירה 5,7142-106-9,דירה בבית קומות,3.0,שישית,63.00,...,NaN,NaN,1970.0,2022.0,4.0,6205792900,1,7142-106,False,NaN
19998,18,19.05.2024,2024-05-19T00:00:00,"קדושי קהיר 7, בת ים",קדושי קהיר 7,7148-138-1,דירה בבית קומות,4.0,חמישית,97.00,...,NaN,NaN,2024.0,NaN,NaN,6205826300,1,7148-138,False,NaN
19999,19,16.05.2024,2024-05-16T00:00:00,"החשמונאים 74, בת ים",החשמונאים 74,7130-198-6,דירה בבית קומות,3.0,שניה,42.47,...,NaN,NaN,1950.0,2026.0,2.0,6206056900,1,7130-198,False,NaN