In [1]:
import geopandas as gpd
import pandas as pd
from tqdm import tqdm
import requests
import numpy as np

In [2]:
url = 'https://www.nadlan.gov.il/Nadlan.REST/Main/GetAssestAndDeals'

list_res=[]

In [3]:
city_name = "הרצליה"
objid = "6400"
X = 184077.07542654
Y= 675219.6943939

In [4]:
df_full=pd.DataFrame()

In [5]:
for pagenum in tqdm(range(1,2)):
    data = {"MoreAssestsType":0,"FillterRoomNum":0,"GridDisplayType":0,
            "ResultLable":city_name,
            "ResultType":1,
            "ObjectID":objid,"ObjectIDType":"text","ObjectKey":"UNIQ_ID",
            "DescLayerID":"SETL_MID_POINT","Alert":None,
            "X":X,
            "Y":Y,
            "Gush":"","Parcel":"","showLotParcel":True,
            "showLotAddress":True,"OriginalSearchString":city_name,"MutipuleResults":False,
            "ResultsOptions":None,
            "CurrentLavel":2,
            "Navs":[{"text":"מחוז תל אביב - יפו","url":None,"order":1}],
            "QueryMapParams":{"QueryToRun":None,"QueryObjectID":objid,"QueryObjectType":"number",
                              "QueryObjectKey":"SETL_CODE","QueryDescLayerID":"KSHTANN_SETL_AREA","SpacialWhereClause":None},
            "isHistorical":True,
            "PageNo":pagenum,
            "OrderByFilled":"DEALDATETIME","OrderByDescending":True,"Distance":0}
    result = requests.post(url, json=data).json()
    list_res.append(result)

for r in list_res:
    df= pd.DataFrame(r["AllResults"])
    df_full = pd.concat([df,df_full])

100%|█████████████████████████████████████████████| 1/1 [00:04<00:00,  4.26s/it]

In [6]:
df_full

,DEALDATE,DEALDATETIME,FULLADRESS,DISPLAYADRESS,GUSH,DEALNATUREDESCRIPTION,ASSETROOMNUM,FLOORNO,DEALNATURE,DEALAMOUNT,NEWPROJECTTEXT,PROJECTNAME,BUILDINGYEAR,YEARBUILT,BUILDINGFLOORS,KEYVALUE,TYPE,POLYGON_ID,TREND_IS_NEGATIVE,TREND_FORMAT
0,28.05.2024,2024-05-28T00:00:00,"אבן גבירול 26, הרצלייה",אבן גבירול 26,6527-387-37,דירה בבית קומות,4,שניה,104,"2,650,000",,None,1960,,3,9185787758,1,6527-387,False,
1,22.05.2024,2024-05-22T00:00:00,,,6529-93-5,דירה בבית קומות,3,ראשונה,78,"2,900,000",,None,2022,,None,9185705248,2,6529-93,False,
2,22.05.2024,2024-05-22T00:00:00,,,6663-207-46,None,5,שמינית,176,"7,130,000",1,None,None,,None,11171527414,2,6663-207,False,
3,21.05.2024,2024-05-21T00:00:00,,,6663-207-47,דירה בבית קומות,4,ראשונה,102,"3,750,000",,None,None,,None,9185680976,2,6663-207,False,
4,20.05.2024,2024-05-20T00:00:00,,,6663-207-45,None,4,ראשונה,102,"3,744,000",1,None,None,,None,11171527413,2,6663-207,False,
5,19.05.2024,2024-05-19T00:00:00,"דון יוסף הנשיא 19, הרצלייה",דון יוסף הנשיא 19,6527-373-12,דירה בבית קומות,3,שלישית,60.20,"2,500,000",,None,1970,,4,9185299950,1,6527-373,False,
6,19.05.2024,2024-05-19T00:00:00,"אריה לייב יפה 52, הרצלייה",אריה לייב יפה 52,6536-799-7,דירה בבית קומות,5,חמישית,122,"4,006,000",,None,1980,2027,3,9185494126,1,6536-799,False,
7,16.05.2024,2024-05-16T00:00:00,,,6663-207-48,דירה בבית קומות,3,חמישית,74,"3,186,000",,None,None,,None,9185893430,2,6663-207,False,
8,15.05.2024,2024-05-15T00:00:00,"זיסו 14, הרצלייה",זיסו 14,6577-153-32,דירה בבית קומות,3,שניה,53.30,"1,075,000",,None,1970,,4,9184864682,1,6577-153,False,65% ב 5.3 שנים
9,15.05.2024,2024-05-15T00:00:00,,,6663-207-44,None,3,חמישית,74,"3,180,000",1,None,None,,None,11171527412,2,6663-207,False,
10,07.05.2024,2024-05-07T00:00:00,"סוקולוב 77, הרצלייה",סוקולוב 77,6532-357-13,דירה בבית קומות,4,שלישית,90,"3,500,000",,None,2017,,8,9184424012,1,6532-357,False,45% ב 6.7 שנים
11,05.05.2024,2024-05-05T00:00:00,,,6525-260-2,ללא תיכנון,,None,,"133,333,000",,None,None,,None,9185708356,2,6525-260,False,
12,01.05.2024,2024-05-01T00:00:00,,,6423-30-15,None,5,שלישית,149,"5,500,000",1,None,None,,None,11171522188,2,6423-30,False,
13,24.04.2024,2024-04-24T00:00:00,"שמואל הנגיד 20, הרצלייה",שמואל הנגיד 20,6527-303-10,דירה בבית קומות,4,שלישית,61.80,"3,750,000",,None,2022,,3,9183862204,1,6527-303,False,
14,21.04.2024,2024-04-21T00:00:00,"שמואל הנגיד 20, הרצלייה",שמואל הנגיד 20,6527-303-11,דירה בבית קומות,4,שלישית,109,"3,775,000",,None,2022,,3,9183861612,1,6527-303,False,16% ב 1.7 שנים
15,21.04.2024,2024-04-21T00:00:00,"ויצמן 22, הרצלייה",ויצמן 22,6534-57-4,דירה בבית קומות,4,ראשונה,78.10,"2,875,000",,None,1960,,3,9183824390,1,6534-57,False,
16,21.04.2024,2024-04-21T00:00:00,"העצמאות 103, הרצלייה",העצמאות 103,6537-221-15,דירה בבית קומות,5,ראשונה,123.01,"3,300,000",,None,1992,,5,9183932356,1,6537-221,False,
17,19.04.2024,2024-04-19T00:00:00,"בני בנימין 18, הרצלייה",בני בנימין 18,6528-45-7,דירה בבית קומות,3,שניה,75,"2,550,000",,None,1970,2024,3,9185112508,1,6528-45,False,
18,18.04.2024,2024-04-18T00:00:00,,,6529-93-6,דירה בבית קומות,5,שביעית,131,"3,750,000",,None,2022,,None,9183795086,2,6529-93,False,
19,18.04.2024,2024-04-18T00:00:00,"אמה טאובר 4, הרצלייה",אמה טאובר 4,6536-906-41,דירה בבית קומות,4,שלישית,96,"3,650,000",,None,2002,,7,9183499012,1,6536-906,False,62% ב 10 שנים

In [ ]:
df_full=pd.DataFrame()
list_res=0
for start_n in np.arange(1,2001,200):
    
    for pagenum in tqdm(range(start_n,start_n+200)):
        data = {"MoreAssestsType":0,"FillterRoomNum":0,"GridDisplayType":0,
            "ResultLable":city_name,
            "ResultType":1,
            "ObjectID":objid,"ObjectIDType":"text","ObjectKey":"UNIQ_ID",
            "DescLayerID":"SETL_MID_POINT","Alert":None,
            "X":X,
            "Y":Y,
            "Gush":"","Parcel":"","showLotParcel":True,
            "showLotAddress":True,"OriginalSearchString":city_name,"MutipuleResults":False,
            "ResultsOptions":None,
            "CurrentLavel":2,
            "Navs":[{"text":"מחוז תל אביב - יפו","url":None,"order":1}],
            "QueryMapParams":{"QueryToRun":None,"QueryObjectID":objid,"QueryObjectType":"number",
                              "QueryObjectKey":"SETL_CODE","QueryDescLayerID":"KSHTANN_SETL_AREA","SpacialWhereClause":None},
            "isHistorical":True,
            "PageNo":pagenum,
            "OrderByFilled":"DEALDATETIME","OrderByDescending":True,"Distance":0}
        result = requests.post(url, json=data).json()
        list_res.append(result)
    
    for r in list_res:
        df= pd.DataFrame(r["AllResults"])
        df_full = pd.concat([df,df_full])
    df_full.to_csv(f"herzelia_nadlan_pages{start_n}_{start_n+200}.csv")

100%|█████████████████████████████████████████| 200/200 [14:24<00:00,  4.32s/it]
100%|█████████████████████████████████████████| 200/200 [14:12<00:00,  4.26s/it]
100%|█████████████████████████████████████████| 200/200 [14:36<00:00,  4.38s/it]
100%|█████████████████████████████████████████| 200/200 [14:00<00:00,  4.20s/it]
100%|█████████████████████████████████████████| 200/200 [14:16<00:00,  4.28s/it]
100%|█████████████████████████████████████████| 200/200 [16:12<00:00,  4.86s/it]
100%|█████████████████████████████████████████| 200/200 [14:26<00:00,  4.33s/it]
100%|█████████████████████████████████████████| 200/200 [13:26<00:00,  4.03s/it]
 75%|██████████████████████████████▊          | 150/200 [10:17<03:22,  4.04s/it]

In [3]:
start_n=801

data = pd.read_csv(f"herzelia_nadlan_pages{start_n}_{start_n+200}.csv")

data = data.drop_duplicates()

# df_full=pd.DataFrame()

data

,Unnamed: 0,DEALDATE,DEALDATETIME,FULLADRESS,DISPLAYADRESS,GUSH,DEALNATUREDESCRIPTION,ASSETROOMNUM,FLOORNO,DEALNATURE,...,NEWPROJECTTEXT,PROJECTNAME,BUILDINGYEAR,YEARBUILT,BUILDINGFLOORS,KEYVALUE,TYPE,POLYGON_ID,TREND_IS_NEGATIVE,TREND_FORMAT
0,0,18.08.2003,2003-08-18T00:00:00,"צמרות 2, הרצלייה",צמרות 2,6546-858-109,דירה בבית קומות,4.0,עשירית,121.60,...,NaN,NaN,1998.0,NaN,17.0,7630255662,1,6546-858,False,NaN
1,1,18.08.2003,2003-08-18T00:00:00,"צמרות 10, הרצלייה",צמרות 10,6545-38-226,דירה בבית קומות,4.5,ראשונה,121.10,...,NaN,NaN,2000.0,NaN,29.0,7630255070,1,6545-38,False,NaN
2,2,18.08.2003,2003-08-18T00:00:00,"אברהם שטרן 6, הרצלייה",אברהם שטרן 6,6546-843-4,NaN,2.0,ראשונה,49.32,...,NaN,NaN,1967.0,NaN,4.0,7629980382,1,6546-843,False,NaN
3,3,18.08.2003,2003-08-18T00:00:00,"העלומים 5, הרצלייה",העלומים 5,6663-294-10,NaN,4.0,שלישית,89.89,...,NaN,NaN,1970.0,NaN,3.0,7630061560,1,6663-294,False,NaN
4,4,17.08.2003,2003-08-17T00:00:00,"שניאור זלמן 7, הרצלייה",שניאור זלמן 7,6526-189-20,NaN,5.0,ראשונה,107.00,...,NaN,NaN,1993.0,NaN,5.0,7629687934,1,6526-189,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,15,21.04.2024,2024-04-21T00:00:00,"ויצמן 22, הרצלייה",ויצמן 22,6534-57-4,דירה בבית קומות,4.0,ראשונה,78.10,...,NaN,NaN,1960.0,NaN,3.0,9183824390,1,6534-57,False,NaN
19996,16,21.04.2024,2024-04-21T00:00:00,"העצמאות 103, הרצלייה",העצמאות 103,6537-221-15,דירה בבית קומות,5.0,ראשונה,123.01,...,NaN,NaN,1992.0,NaN,5.0,9183932356,1,6537-221,False,NaN
19997,17,19.04.2024,2024-04-19T00:00:00,"בני בנימין 18, הרצלייה",בני בנימין 18,6528-45-7,דירה בבית קומות,3.0,שניה,75.00,...,NaN,NaN,1970.0,2024.0,3.0,9185112508,1,6528-45,False,NaN
19998,18,18.04.2024,2024-04-18T00:00:00,NaN,NaN,6529-93-6,דירה בבית קומות,5.0,שביעית,131.00,...,NaN,NaN,2022.0,NaN,NaN,9183795086,2,6529-93,False,NaN
19999,19,18.04.2024,2024-04-18T00:00:00,"אמה טאובר 4, הרצלייה",אמה טאובר 4,6536-906-41,דירה בבית קומות,4.0,שלישית,96.00,...,NaN,NaN,2002.0,NaN,7.0,9183499012,1,6536-906,False,62% ב 10 שנים