In [1]:
import geopandas as gpd
import pandas as pd
from tqdm import tqdm
import requests
import numpy as np

In [2]:
url = 'https://www.nadlan.gov.il/Nadlan.REST/Main/GetAssestAndDeals'

list_res=[]

In [3]:
city_name = "חולון"
objid = "6600"
X=179549.36772654
Y=657909.9234939

In [4]:
df_full=pd.DataFrame()

In [9]:
for pagenum in tqdm(range(1,2)):
    data = {"MoreAssestsType":0,"FillterRoomNum":0,"GridDisplayType":0,
            "ResultLable":city_name,
            "ResultType":1,
            "ObjectID":objid,"ObjectIDType":"text","ObjectKey":"UNIQ_ID",
            "DescLayerID":"SETL_MID_POINT","Alert":None,
            "X":X,
            "Y":Y,
            "Gush":"","Parcel":"","showLotParcel":True,
            "showLotAddress":True,"OriginalSearchString":city_name,"MutipuleResults":False,
            "ResultsOptions":None,
            "CurrentLavel":2,
            "Navs":[{"text":None,"url":None,"order":1}],
            "QueryMapParams":{"QueryToRun":None,"QueryObjectID":objid,"QueryObjectType":"number",
                              "QueryObjectKey":"SETL_CODE","QueryDescLayerID":"KSHTANN_SETL_AREA","SpacialWhereClause":None},
            "isHistorical":True,
            "PageNo":pagenum,
            "OrderByFilled":"DEALDATETIME","OrderByDescending":True,"Distance":0}
    result = requests.post(url, json=data).json()
    list_res.append(result)

for r in list_res:
    df= pd.DataFrame(r["AllResults"])
    df_full = pd.concat([df,df_full])

100%|█████████████████████████████████████████████| 1/1 [00:07<00:00,  7.51s/it]

In [10]:
df_full

,DEALDATE,DEALDATETIME,FULLADRESS,DISPLAYADRESS,GUSH,DEALNATUREDESCRIPTION,ASSETROOMNUM,FLOORNO,DEALNATURE,DEALAMOUNT,NEWPROJECTTEXT,PROJECTNAME,BUILDINGYEAR,YEARBUILT,BUILDINGFLOORS,KEYVALUE,TYPE,POLYGON_ID,TREND_IS_NEGATIVE,TREND_FORMAT
0,30.05.2024,2024-05-30T00:00:00,"נעמי שמר 12, חולון",נעמי שמר 12,6872-17-30,דירה בבית קומות,5,שביעית,120.88,"3,170,000",,None,2009,,11,3600917414,1,6872-17,False,70% ב 12.9 שנים
1,30.05.2024,2024-05-30T00:00:00,"רבינוביץ יהושע 83, חולון",רבינוביץ יהושע 83,7183-25-7,דירה בבית קומות,4,שלישית,99,"2,250,000",,None,1995,,10,3600921967,1,7183-25,False,207% ב 19.4 שנים
2,27.05.2024,2024-05-27T00:00:00,"הדר 26, חולון",הדר 26,6996-127-12,דירה בבית קומות,4,שישית,74.36,"2,270,000",,None,1997,,6,3600831284,1,6996-127,False,145% ב 16.2 שנים
3,26.05.2024,2024-05-26T00:00:00,"רמת הגולן 33, חולון",רמת הגולן 33,7342-46-31,דירה בבית קומות,3,רביעית,61,"1,800,000",,None,1970,,4,3600812405,1,7342-46,False,
4,23.05.2024,2024-05-23T00:00:00,"יהודה הלוי 13, חולון",יהודה הלוי 13,7171-84-10,דירה בבית קומות,3,רביעית,57.73,"1,650,000",,None,1970,,4,3600803995,1,7171-84,False,15% ב 2.3 שנים
5,23.05.2024,2024-05-23T00:00:00,"סוקולוב 116, חולון",סוקולוב 116,7169-128-7,דירה בבית קומות,2,ראשונה,61.14,"1,740,000",,None,1960,,2,3600811187,1,7169-128,False,45% ב 4.6 שנים
6,21.05.2024,2024-05-21T00:00:00,"אחד במאי 50, חולון",אחד במאי 50,7176-107-3,None,2,ראשונה,38,"2,120,000",,None,1960,,3,3600692519,1,7176-107,False,
7,20.05.2024,2024-05-20T00:00:00,"הדס 20, חולון",הדס 20,6870-81-28,דירה בבית קומות,4,שביעית,124.15,"3,100,000",,None,2008,,13,3600842768,1,6870-81,False,
8,20.05.2024,2024-05-20T00:00:00,"אמיר דרורי 2, חולון",אמיר דרורי 2,6870-84-42,דירה בבית קומות,4,קומה ‎11‏,108.75,"2,800,000",,None,2005,,15,3600807852,1,6870-84,False,75% ב 14.5 שנים
9,20.05.2024,2024-05-20T00:00:00,"חנקין 36, חולון",חנקין 36,7168-166-12,דירה בבית קומות,3.5,רביעית,58,"2,000,000",,None,1950,,3,3600618308,1,7168-166,False,
10,19.05.2024,2024-05-19T00:00:00,"התחייה 22, חולון",התחייה 22,6021-949-22,דירה בבית קומות,4,שישית,97.22,"2,450,000",,None,1970,,9,3600561120,1,6021-949,False,
11,19.05.2024,2024-05-19T00:00:00,"הצנחנים 3, חולון",הצנחנים 3,7167-74-5,דירה בבית קומות,5,חמישית,173,"3,930,000",,None,1951,2026,1,3600581275,1,7167-74,False,
12,19.05.2024,2024-05-19T00:00:00,"עמק דותן 1, חולון",עמק דותן 1,7341-32-13,דירה בבית קומות,3,רביעית,73,"1,700,000",,None,1970,,7,3600542763,1,7341-32,False,
13,16.05.2024,2024-05-16T00:00:00,"ארלוזורוב 17, חולון",ארלוזורוב 17,7170-44-19,דירה בבית קומות,3,שניה,78,"2,455,000",,None,1930,2026,6,3600733931,1,7170-44,False,
14,15.05.2024,2024-05-15T00:00:00,"פרופ' שור 45, חולון",פרופ' שור 45,6779-55-21,דירה בבית קומות,5,שישית,98,"1,175,000",,None,1989,,9,3600488910,1,6779-55,False,135% ב 15.5 שנים
15,15.05.2024,2024-05-15T00:00:00,"דב הוז 67, חולון",דב הוז 67,7162-202-8,דירה בבית קומות,3,שניה,67.59,"1,720,000",,None,1970,,3,3600519998,1,7162-202,False,
16,15.05.2024,2024-05-15T00:00:00,"ארלוזורוב 17, חולון",ארלוזורוב 17,7170-44-18,None,5,רביעית,130,"3,570,000",1,None,1930,,6,11171539210,1,7170-44,False,
17,13.05.2024,2024-05-13T00:00:00,"הגר""א 26, חולון","הגר""א 26",7162-229-10,דירה בבית קומות,4,שלישית,72.84,"1,790,000",,None,1995,,4,3600426734,1,7162-229,False,28% ב 7.5 שנים
18,12.05.2024,2024-05-12T00:00:00,"דוד אלעזר 7, חולון",דוד אלעזר 7,6020-318-3,דירה בבית קומות,3,ראשונה,67,"2,075,000",,None,2025,,1,3600652557,1,6020-318,False,
19,10.05.2024,2024-05-10T00:00:00,"חנקין 117, חולון",חנקין 117,6021-522-24,דירה בבית קומות,2,ראשונה,36.60,"1,740,000",,None,1960,,2,3600477426,1,6021-522,False,16% ב 1 שנים
0,30.05.2024,2024-05-30T00:00:00,"נעמי שמר 12, חולון",נעמי שמר 12,6872-17-30,דירה בבית קומות,5,שביעית,120.88,"3,170,000",,None,2009,,11,3600917414,1,6872-17,False,70% ב 12.9 שנים
1,30.05.2024,2024-05-30T00:00:00,"רבינוביץ יהושע 83, חולון",רבינוביץ יהושע 83,7183-25-7,דירה בבית קומות,4,שלישית,99,"2,250,000",,None,1995,,10,3600921967,1,7183-25,False,207% ב 19.4 שנים
2,27.05.2024,2024-05-27T00:00:00,"הדר 26, חולון",הדר 26,6996-127-12,דירה בבית קומות,4,שישית,74.36,"2,270,000",,None,1997,,6,3600831284,1,6996-127,False,145% ב 16.2 שנים
3,26.05.2024,2024-05-26T00:00:00,"רמת הגולן 33, חולון",רמת הגולן 33,7342-46-31,דירה בבית קומות,3,רביעית,61,"1,800,000",,None,1970,,4,3600812405,1,7342-46,False,
4,23.05.2024,2024-05-23T00:00:00,"יהודה הלוי 13, חולון",יהודה הלוי 13,7171-84-10,דירה בבית קומות,3,רביעית,57.73,"1,650,000",,None,1970,,4,3600803995,1,7171-84,False,15% ב 2.3 שנים
5,23.05.2024,2024-05-23T00:00:00,"סוקולוב 116, חולון",סוקולוב 116,7169-128-7,דירה בבית קומות,2,ראשונה,61.14,"1,740,000",,None,1960,,2,3600811187,1,7169-128,False,45% ב 4.6 שנים
6,21.05.2024,2024-05-21T00:00:00,"אחד במאי 50, חולון",אחד במאי 50,7176-107-3,None,2,ראשונה,38,"2,120,000",,None,1960,,3,3600692519,1,7176-107,False,
7,20.05.2024,2024-05-20T00:00:00,"הדס 20, חולון",הדס 20,6870-81-28,דירה בבית קומות,4,שביעית,124.15,"3,100,000",,None,2008,,13,3600842768,1,6870-81,False,
8,20.05.2024,2024-05-20T00:00:00,"אמיר דרורי 2, חולון",אמיר דרורי 2,6870-84-42,דירה בבית קומות,4,קומה ‎11‏,108.75,"2,800,000",,None,2005,,15,3600807852,1,6870-84,False,75% ב 14.5 שנים
9,20.05.2024,2024-05-20T00:00:00,"חנקין 36, חולון",חנקין 36,7168-166-12,דירה בבית קומות,3.5,רביעית,58,"2,000,000",,None,1950,,3,3600618308,1,7168-166,False,
10,19.05.2024,2024-05-19T00:00:00,"התחייה 22, חולון",התחייה 22,6021-949-22,דירה בבית קומות,4,שישית,97.22,"2,450,000",,None,1970,,9,3600561120,1,6021-949,False,
11,19.05.2024,2024-05-19T00:00:00,"הצנחנים 3, חולון",הצנחנים 3,7167-74-5,דירה בבית קומות,5,חמישית,173,"3,930,000",,None,1951,2026,1,3600581275,1,7167-74,False,
12,19.05.2024,2024-05-19T00:00:00,"עמק דותן 1, חולון",עמק דותן 1,7341-32-13,דירה בבית קומות,3,רביעית,73,"1,700,000",,None,1970,,7,3600542763,1,7341-32,False,
13,16.05.2024,2024-05-16T00:00:00,"ארלוזורוב 17, חולון",ארלוזורוב 17,7170-44-19,דירה בבית קומות,3,שניה,78,"2,455,000",,None,1930,2026,6,3600733931,1,7170-44,False,
14,15.05.2024,2024-05-15T00:00:00,"פרופ' שור 45, חולון",פרופ' שור 45,6779-55-21,דירה בבית קומות,5,שישית,98,"1,175,000",,None,1989,,9,3600488910,1,6779-55,False,135% ב 15.5 שנים
15,15.05.2024,2024-05-15T00:00:00,"דב הוז 67, חולון",דב הוז 67,7162-202-8,דירה בבית קומות,3,שניה,67.59,"1,720,000",,None,1970,,3,3600519998,1,7162-202,False,
16,15.05.2024,2024-05-15T00:00:00,"ארלוזורוב 17, חולון",ארלוזורוב 17,7170-44-18,None,5,רביעית,130,"3,570,000",1,None,1930,,6,11171539210,1,7170-44,False,
17,13.05.2024,2024-05-13T00:00:00,"הגר""א 26, חולון","הגר""א 26",7162-229-10,דירה בבית קומות,4,שלישית,72.84,"1,790,000",,None,1995,,4,3600426734,1,7162-229,False,28% ב 7.5 שנים
18,12.05.2024,2024-05-12T00:00:00,"דוד אלעזר 7, חולון",דוד אלעזר 7,6020-318-3,דירה בבית קומות,3,ראשונה,67,"2,075,000",,None,2025,,1,3600652557,1,6020-318,False,
19,10.05.2024,2024-05-10T00:00:00,"חנקין 117, חולון",חנקין 117,6021-522-24,דירה בבית קומות,2,ראשונה,36.60,"1,740,000",,None,1960,,2,3600477426,1,6021-522,False,16% ב 1 שנים
0,30.05.2024,2024-05-30T00:00:00,"נעמי שמר 12, חולון",נעמי שמר 12,6872-17-30,דירה בבית קומות,5,שביעית,120.88,"3,170,000",,None,2009,,11,3600917414,1,6872-17,False,70% ב 12.9 שנים
1,30.05.2024,2024-05-30T00:00:00,"רבינוביץ יהושע 83, חולון",רבינוביץ יהושע 83,7183-25-7,דירה בבית קומות,4,שלישית,99,"2,250,000",,None,1995,,10,3600921967,1,7183-25,False,207% ב 19.4 שנים
2,27.05.2024,2024-05-27T00:00:00,"הדר 26, חולון",הדר 26,6996-127-12,דירה בבית קומות,4,שישית,74.36,"2,270,000",,None,1997,,6,3600831284,1,6996-127,False,145% ב 16.2 שנים
3,26.05.2024,2024-05-26T00:00:00,"רמת הגולן 33, חולון",רמת הגולן 33,7342-46-31,דירה בבית קומות,3,רביעית,61,"1,800,000",,None,1970,,4,3600812405,1,7342-46,False,
4,23.05.2024,2024-05-23T00:00:00,"יהודה הלוי 13, חולון",יהודה הלוי 13,7171-84-10,דירה בבית קומות,3,רביעית,57.73,"1,650,000",,None,1970,,4,3600803995,1,7171-84,False,15% ב 2.3 שנים
5,23.05.2024,2024-05-23T00:00:00,"סוקולוב 116, חולון",סוקולוב 116,7169-128-7,דירה בבית קומות,2,ראשונה,61.14,"1,740,000",,None,1960,,2,3600811187,1,7169-128,False,45% ב 4.6 שנים
6,21.05.2024,2024-05-21T00:00:00,"אחד במאי 50, חולון",אחד במאי 50,7176-107-3,None,2,ראשונה,38,"2,120,000",,None,1960,,3,3600692519,1,7176-107,False,
7,20.05.2024,2024-05-20T00:00:00,"הדס 20, חולון",הדס 20,6870-81-28,דירה בבית קומות,4,שביעית,124.15,"3,100,000",,None,2008,,13,3600842768,1,6870-81,False,
8,20.05.2024,2024-05-20T00:00:00,"אמיר דרורי 2, חולון",אמיר דרורי 2,6870-84-42,דירה בבית קומות,4,קומה ‎11‏,108.75,"2,800,000",,None,2005,,15,3600807852,1,6870-84,False,75% ב 14.5 שנים
9,20.05.2024,2024-05-20T00:00:00,"חנקין 36, חולון",חנקין 36,7168-166-12,דירה בבית קומות,3.5,רביעית,58,"2,000,000",,None,1950,,3,3600618308,1,7168-166,False,
10,19.05.2024,2024-05-19T00:00:00,"התחייה 22, חולון",התחייה 22,6021-949-22,דירה בבית קומות,4,שישית,97.22,"2,450,000",,None,1970,,9,3600561120,1,6021-949,False,
11,19.05.2024,2024-05-19T00:00:00,"הצנחנים 3, חולון",הצנחנים 3,7167-74-5,דירה בבית קומות,5,חמישית,173,"3,930,000",,None,1951,2026,1,3600581275,1,7167-74,False,
12,19.05.2024,2024-05-19T00:00:00,"עמק דותן 1, חולון",עמק דותן 1,7341-32-13,דירה בבית קומות,3,רביעית,73,"1,700,000",,None,1970,,7,3600542763,1,7341-32,False,
13,16.05.2024,2024-05-16T00:00:00,"ארלוזורוב 17, חולון",ארלוזורוב 17,7170-44-19,דירה בבית קומות,3,שניה,78,"2,455,000",,None,1930,2026,6,3600733931,1,7170-44,False,
14,15.05.2024,2024-05-15T00:00:00,"פרופ' שור 45, חולון",פרופ' שור 45,6779-55-21,דירה בבית קומות,5,שישית,98,"1,175,000",,None,1989,,9,3600488910,1,6779-55,False,135% ב 15.5 שנים
15,15.05.2024,2024-05-15T00:00:00,"דב הוז 67, חולון",דב הוז 67,7162-202-8,דירה בבית קומות,3,שניה,67.59,"1,720,000",,None,1970,,3,3600519998,1,7162-202,False,
16,15.05.2024,2024-05-15T00:00:00,"ארלוזורוב 17, חולון",ארלוזורוב 17,7170-44-18,None,5,רביעית,130,"3,570,000",1,None,1930,,6,11171539210,1,7170-44,False,
17,13.05.2024,2024-05-13T00:00:00,"הגר""א 26, חולון","הגר""א 26",7162-229-10,דירה בבית קומות,4,שלישית,72.84,"1,790,000",,None,1995,,4,3600426734,1,7162-229,False,28% ב 7.5 שנים
18,12.05.2024,2024-05-12T00:00:00,"דוד אלעזר 7, חולון",דוד אלעזר 7,6020-318-3,דירה בבית קומות,3,ראשונה,67,"2,075,000",,None,2025,,1,3600652557,1,6020-318,False,
19,10.05.2024,2024-05-10T00:00:00,"חנקין 117, חולון",חנקין 117,6021-522-24,דירה בבית קומות,2,ראשונה,36.60,"1,740,000",,None,1960,,2,3600477426,1,6021-522,False,16% ב 1 שנים

In [ ]:
df_full=pd.DataFrame()
for start_n in np.arange(1,2001,200):
    
    for pagenum in tqdm(range(start_n,start_n+200)):
        data = {"MoreAssestsType":0,"FillterRoomNum":0,"GridDisplayType":0,
            "ResultLable":city_name,
            "ResultType":1,
            "ObjectID":objid,"ObjectIDType":"text","ObjectKey":"UNIQ_ID",
            "DescLayerID":"SETL_MID_POINT","Alert":None,
            "X":X,
            "Y":Y,
            "Gush":"","Parcel":"","showLotParcel":True,
            "showLotAddress":True,"OriginalSearchString":city_name,"MutipuleResults":False,
            "ResultsOptions":None,
            "CurrentLavel":2,
            "Navs":[{"text":None,"url":None,"order":1}],
            "QueryMapParams":{"QueryToRun":None,"QueryObjectID":objid,"QueryObjectType":"number",
                              "QueryObjectKey":"SETL_CODE","QueryDescLayerID":"KSHTANN_SETL_AREA","SpacialWhereClause":None},
            "isHistorical":True,
            "PageNo":pagenum,
            "OrderByFilled":"DEALDATETIME","OrderByDescending":True,"Distance":0}
        result = requests.post(url, json=data).json()
        list_res.append(result)
    
    for r in list_res:
        df= pd.DataFrame(r["AllResults"])
        df_full = pd.concat([df,df_full])
    df_full.to_csv(f"holon_nadlan_pages{start_n}_{start_n+200}.csv")

100%|█████████████████████████████████████████| 200/200 [25:17<00:00,  7.59s/it]
100%|█████████████████████████████████████████| 200/200 [25:43<00:00,  7.72s/it]
100%|█████████████████████████████████████████| 200/200 [25:48<00:00,  7.74s/it]
100%|█████████████████████████████████████████| 200/200 [28:57<00:00,  8.69s/it]
100%|█████████████████████████████████████████| 200/200 [25:05<00:00,  7.53s/it]
  4%|█▋                                         | 8/200 [01:01<24:01,  7.51s/it]

In [ ]:
o

In [5]:
start_n=801

data = pd.read_csv(f"holon_nadlan_pages{start_n}_{start_n+200}.csv")

data = data.drop_duplicates()

# df_full=pd.DataFrame()

data

,Unnamed: 0,DEALDATE,DEALDATETIME,FULLADRESS,DISPLAYADRESS,GUSH,DEALNATUREDESCRIPTION,ASSETROOMNUM,FLOORNO,DEALNATURE,...,NEWPROJECTTEXT,PROJECTNAME,BUILDINGYEAR,YEARBUILT,BUILDINGFLOORS,KEYVALUE,TYPE,POLYGON_ID,TREND_IS_NEGATIVE,TREND_FORMAT
0,0,15.11.2013,2013-11-15T00:00:00,"נורדאו 7, חולון",נורדאו 7,7167-118-3,דירה בבית קומות,4.0,שניה,63.20,...,NaN,NaN,1960.0,NaN,3.0,3286494049,1,7167-118,False,NaN
1,1,15.11.2013,2013-11-15T00:00:00,"יוסף הנשיא 3, חולון",יוסף הנשיא 3,7171-117-6,דירה בבית קומות,3.0,שניה,65.08,...,NaN,NaN,2004.0,NaN,4.0,3286496920,1,7171-117,False,86% ב 9.5 שנים
2,2,14.11.2013,2013-11-14T00:00:00,"התחייה 19, חולון",התחייה 19,6021-940-45,דירה בבית קומות,2.5,רביעית,42.40,...,NaN,NaN,1960.0,NaN,4.0,3287017789,1,6021-940,False,97% ב 6 שנים
3,3,14.11.2013,2013-11-14T00:00:00,"יצחק וולקני 13, חולון",יצחק וולקני 13,6049-269-12,דירה בבית קומות,3.0,שלישית,57.23,...,NaN,NaN,1970.0,NaN,3.0,3286500777,1,6049-269,False,84% ב 7.3 שנים
4,4,14.11.2013,2013-11-14T00:00:00,NaN,NaN,6869-11-27,דירה בבית קומות,4.0,קומה ‎7‏,113.15,...,NaN,NaN,NaN,NaN,NaN,3286692177,2,6869-11,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,15,15.05.2024,2024-05-15T00:00:00,"דב הוז 67, חולון",דב הוז 67,7162-202-8,דירה בבית קומות,3.0,שניה,67.59,...,NaN,NaN,1970.0,NaN,3.0,3600519998,1,7162-202,False,NaN
19996,16,15.05.2024,2024-05-15T00:00:00,"ארלוזורוב 17, חולון",ארלוזורוב 17,7170-44-18,NaN,5.0,רביעית,130.00,...,1.0,NaN,1930.0,NaN,6.0,11171539210,1,7170-44,False,NaN
19997,17,13.05.2024,2024-05-13T00:00:00,"הגר""א 26, חולון","הגר""א 26",7162-229-10,דירה בבית קומות,4.0,שלישית,72.84,...,NaN,NaN,1995.0,NaN,4.0,3600426734,1,7162-229,False,28% ב 7.5 שנים
19998,18,12.05.2024,2024-05-12T00:00:00,"דוד אלעזר 7, חולון",דוד אלעזר 7,6020-318-3,דירה בבית קומות,3.0,ראשונה,67.00,...,NaN,NaN,2025.0,NaN,1.0,3600652557,1,6020-318,False,NaN
19999,19,10.05.2024,2024-05-10T00:00:00,"חנקין 117, חולון",חנקין 117,6021-522-24,דירה בבית קומות,2.0,ראשונה,36.60,...,NaN,NaN,1960.0,NaN,2.0,3600477426,1,6021-522,False,16% ב 1 שנים